### ISSUE TITLE
New Google Meet Layout seems to break the sync

### ISSUE THREAD

**Issue by jenom** [LambyPants/google-meet-randomizer#6]
The box returns the message 

> 1. No results found - contact XXX@gmail.com if issue persists.

instead. This is of course expected on such a fundamental layout change. I just wanted you to know.

**Comment by LambyPants** [comment]
Thanks @jenom - will investigate. Does the randomize button work for you or is it just the "resync" button which is affected? 

I did update the extension a few days ago after the layout update so the randomize button should work (at least in US, English language browsers); I am aware of a bug with "resync" reported by another user, but this sounds like it's totally broken for you.

What region are you using the extension? I can try to use a VPN to see if the selectors need tweaking. I am guessing that's the problem since the new version uses `aria-labels` which may be language or region specific.

**Comment by LambyPants** [comment]
@jenom made a change to the selectors in 2.2.1 (should autoupdate if you have it installed) - let me know if that does or doesnt fix it for you.

**Comment by jenom** [comment]
Both resync and randomise work as expected now for me. Thanks a lot!

**Comment by LambyPants** [comment]
Yay np!
